In [248]:
import pandas as pd 
  
# intialise data of lists. 
data = {'A':[1.2,1.4,2.5,3.3], 
        'B':[2.3,1.1,3.0,2.7],
        'C':[2.5,2.5,2.5,2.5],
        'D':['L','R','R','L']} 
  
# Create DataFrame 
df = pd.DataFrame(data) 
  
# Print the output. 
df 

A    B    C  D
0  1.2  2.3  2.5  L
1  1.4  1.1  2.5  R
2  2.5  3.0  2.5  R
3  3.3  2.7  2.5  L

In [249]:
from sklearn import preprocessing

# creating instance of labelencoder
labelencoder = preprocessing.LabelEncoder()
labelencoder.fit(df['D'])
print(list(labelencoder.classes_))

# Assigning numerical values and storing in another column
df['D'] = labelencoder.fit_transform(df['D'])
df

['L', 'R']


A    B    C  D
0  1.2  2.3  2.5  0
1  1.4  1.1  2.5  1
2  2.5  3.0  2.5  1
3  3.3  2.7  2.5  0

In [251]:
from sklearn.preprocessing import KBinsDiscretizer

X=df.to_numpy()
# transform the dataset with KBinsDiscretizer
enc = KBinsDiscretizer(n_bins=3, encode='ordinal',strategy='uniform')
X_binned = enc.fit_transform(X.tolist())
X_binned=X_binned+1

c:\programdata\anaconda3\lib\site-packages\sklearn\preprocessing\_discretization.py:159: UserWarning: Feature 2 is constant and will be replaced with 0.
  "replaced with 0." % jj)


In [252]:
X_binned

array([[1., 2., 1., 1.],
       [1., 1., 1., 3.],
       [2., 3., 1., 3.],
       [3., 3., 1., 1.]])

In [253]:
r,c = X_binned.shape
f = ['A','B','C']
D = []
  
# Create DataFrame 
for i in range(r):
    for j in range(r):
        if i>j and X_binned[i][-1]!=X_binned[j][-1]:
            str1=''
            temp=[]
            fg=0
            for k in range(c-1):
                if X_binned[i][k]!=X_binned[j][k]:
                    if k==0 or str1=="":
                        str1 = str1+f[k]
                        print('{}-{}:{}'.format(i+1,j+1,str1))
                    else:
                        str1 = str1+" "+f[k]
                        print('{}-{}:{}'.format(i+1,j+1,str1))
             
            D.append(str1)

2-1:B
3-1:A
3-1:A B
4-2:A
4-2:A B
4-3:A


In [254]:
D

['B', 'A B', 'A B', 'A']

In [255]:
l=len(D)
core =[]
for i in range(l):
    if len(D[i])==1:
        core.append(D[i])

In [256]:
core

['B', 'A']

In [257]:
t=len(core)
reduct=[]
for i in range(l):
    c=0
    for j in range(t):
        if D[i].find(core[j]) != -1 and len(D[i])>1:
            c=c+1
            
    if c==t:
        reduct=D[i]

In [273]:
reduct

'A B'

In [259]:
# Create reduced DataFrame 
dfr=df[["A","B","D"]] 

# Print reduced DataFrame
dfr

A    B  D
0  1.2  2.3  0
1  1.4  1.1  1
2  2.5  3.0  1
3  3.3  2.7  0

In [274]:
rf=reduct.split(" ")
rf.append("D")
rf

['A', 'B', 'D']

In [276]:
df[rf]

A    B  D
0  1.2  2.3  0
1  1.4  1.1  1
2  2.5  3.0  1
3  3.3  2.7  0

In [287]:
########################## Classical Discernibility Matrix: Reduct ###############################
import warnings
warnings.filterwarnings('ignore')

import pandas as pd 
from sklearn import preprocessing
from sklearn.preprocessing import KBinsDiscretizer
import numpy as np
  
def my_discrn_mat(df,nbin):
    
    
    # creating instance of labelencoder
    labelencoder = preprocessing.LabelEncoder()
    labelencoder.fit(df['D'])
    print('Actual Class labels: ',list(labelencoder.classes_))

    # Assigning numerical values and storing in another column
    df['D'] = labelencoder.fit_transform(df['D'])
    print('\nActual Dataset: \n',df)
    
    X=df.to_numpy()
    # transform the dataset with KBinsDiscretizer
    enc = KBinsDiscretizer(n_bins=3, encode='ordinal',strategy='uniform')
    X_binned = enc.fit_transform(X.tolist())
    X_binned=X_binned+1
    print('\nDiscretized Dataset: \n', X_binned)
    
    r,c = X_binned.shape
    f = ['A','B','C']
    D = []
  
    # Create DataFrame 
    dfm = pd.DataFrame(M) 
    print('\nDiscernibilty Matrix Processing...')
    for i in range(r):
        for j in range(r):
            if i>j and X_binned[i][-1]!=X_binned[j][-1]:
                str1=''
                temp=[]
                fg=0
                for k in range(c-1):
                    if X_binned[i][k]!=X_binned[j][k]:
                        if k==0 or str1=="":
                            str1 = str1+f[k]
                            print('{}-{}:{}'.format(i+1,j+1,str1))
                        else:
                            str1 = str1+" "+f[k]
                            print('{}-{}:{}'.format(i+1,j+1,str1))
             
                D.append(str1)

    print('\nValid entries in Discernibilty Matrix: ',D)
    
    l=len(D)
    core =[]
    for i in range(l):
        if len(D[i])==1:
            core.append(D[i])
    
    print('\nCORE(s): ',core)
    
    t=len(core)
    reduct=[]
    for i in range(l):
        c=0
        for j in range(t):
            if D[i].find(core[j]) != -1 and len(D[i])>1:
                c=c+1
            
        if c==t:
            reduct=D[i]
            
    print('\nREDUCT: ',reduct)
    
    rf=reduct.split(" ")
    rf.append("D")
    
    return df[rf], rf[:-1]
    
######### Entry Main ##########    
# intialise data of lists. 
data = {'A':[1.2,1.4,2.5,3.3], 
        'B':[2.3,1.1,3.0,2.7],
        'C':[2.5,2.5,2.5,2.5],
        'D':['L','R','R','L']} 
  
# Create DataFrame 
df = pd.DataFrame(data) 
  
# Print the output. 
print('\nBefore Reduct Computation: ',df) 
rdf, rf = my_discrn_mat(df,nbin=3) 
print('\nAfter Reduct Computation: ',rdf) 
print('\nObtained Reduct is: ',rf)


Before Reduct Computation:       A    B    C  D
0  1.2  2.3  2.5  L
1  1.4  1.1  2.5  R
2  2.5  3.0  2.5  R
3  3.3  2.7  2.5  L
Actual Class labels:  ['L', 'R']

Actual Dataset: 
      A    B    C  D
0  1.2  2.3  2.5  0
1  1.4  1.1  2.5  1
2  2.5  3.0  2.5  1
3  3.3  2.7  2.5  0

Discretized Dataset: 
 [[1. 2. 1. 1.]
 [1. 1. 1. 3.]
 [2. 3. 1. 3.]
 [3. 3. 1. 1.]]

Discernibilty Matrix Processing...
2-1:B
3-1:A
3-1:A B
4-2:A
4-2:A B
4-3:A

Valid entries in Discernibilty Matrix:  ['B', 'A B', 'A B', 'A']

CORE(s):  ['B', 'A']

REDUCT:  A B

After Reduct Computation:       A    B  D
0  1.2  2.3  0
1  1.4  1.1  1
2  2.5  3.0  1
3  3.3  2.7  0

Obtained Reduct is:  ['A', 'B']


In [6]:
#### Calling Discernibility Matrix-based features selection Algorithm (iff features set is <= 26, that is, A to Z) ####

import pandas as pd 
import time
import my_discrn_mat

######### Entry Main ##########    
# intialise data of lists. 
data = {'A':[1.2,1.4,2.5,3.3], 
        'B':[2.3,1.1,2.0,2.7],
        'C':[2.5,2.5,2.5,2.5],
        'D':['L','R','R','L']} 
  
# Create DataFrame 
df = pd.DataFrame(data) 
nbin=3

# Print the output. 
print('\nBefore Reduct Computation: \n',df) 
t1=time.time()
rdf, rf = my_discrn_mat.my_discrn_mat(df,nbin) 
t2=time.time()-t1
print('\nAfter Reduct Computation: \n',rdf) 
print('\nObtained Reduct is: ',rf)
print('\nTotal execution time for DM: {:.6f} seconds'.format(t2))


Before Reduct Computation: 
      A    B    C  D
0  1.2  2.3  2.5  L
1  1.4  1.1  2.5  R
2  2.5  2.0  2.5  R
3  3.3  2.7  2.5  L
Actual Class labels:  ['L', 'R']

Actual Dataset: 
      A    B    C  D
0  1.2  2.3  2.5  0
1  1.4  1.1  2.5  1
2  2.5  2.0  2.5  1
3  3.3  2.7  2.5  0

Discretized Dataset: 
 [[1. 3. 1. 1.]
 [1. 1. 1. 3.]
 [2. 2. 1. 3.]
 [3. 3. 1. 1.]]

Discernibilty Matrix Processing...
2-1:B
3-1:A B
3-2:Φ
4-1:Φ
4-2:A B
4-3:A B

Valid entries in Discernibilty Matrix:  ['B', 'A B', 'A B', 'A B']

CORE(s):  ['B']

REDUCT:  A B

After Reduct Computation: 
      A    B  D
0  1.2  2.3  0
1  1.4  1.1  1
2  2.5  2.0  1
3  3.3  2.7  0

Obtained Reduct is:  ['A', 'B']

Total execution time for DM: 0.004498 seconds
